// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: verification_status_reject/verification_status_reject.proto

package verification_status_reject

import (
	pagination "github.com/djoonta/kpmasterproto/pagination"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerificationStatusRejectWriteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success  bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Messsage string `protobuf:"bytes,2,opt,name=messsage,proto3" json:"messsage,omitempty"`
}

func (x *VerificationStatusRejectWriteResponse) Reset() {
	*x = VerificationStatusRejectWriteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_verification_status_reject_verification_status_reject_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerificationStatusRejectWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationStatusRejectWriteResponse) ProtoMessage() {}

func (x *VerificationStatusRejectWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_verification_status_reject_verification_status_reject_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationStatusRejectWriteResponse.ProtoReflect.Descriptor instead.
func (*VerificationStatusRejectWriteResponse) Descriptor() ([]byte, []int) {
	return file_verification_status_reject_verification_status_reject_proto_rawDescGZIP(), []int{0}
}

func (x *VerificationStatusRejectWriteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VerificationStatusRejectWriteResponse) GetMesssage() string {
	if x != nil {
		return x.Messsage
	}
	return ""
}

type VerificationStatusRejectInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	UpdatedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *VerificationStatusRejectInfo) Reset() {
	*x = VerificationStatusRejectInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_verification_status_reject_verification_status_reject_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerificationStatusRejectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationStatusRejectInfo) ProtoMessage() {}

func (x *VerificationStatusRejectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_verification_status_reject_verification_status_reject_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationStatusRejectInfo.ProtoReflect.Descriptor instead.
func (*VerificationStatusRejectInfo) Descriptor() ([]byte, []int) {
	return file_verification_status_reject_verification_status_reject_proto_rawDescGZIP(), []int{1}
}

func (x *VerificationStatusRejectInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VerificationStatusRejectInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VerificationStatusRejectInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VerificationStatusRejectInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type VerificationStatusRejectFindIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *VerificationStatusRejectFindIDRequest) Reset() {
	*x = VerificationStatusRejectFindIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_verification_status_reject_verification_status_reject_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerificationStatusRejectFindIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationStatusRejectFindIDRequest) ProtoMessage() {}

func (x *VerificationStatusRejectFindIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_verification_status_reject_verification_status_reject_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationStatusRejectFindIDRequest.ProtoReflect.Descriptor instead.
func (*VerificationStatusRejectFindIDRequest) Descriptor() ([]byte, []int) {
	return file_verification_status_reject_verification_status_reject_proto_rawDescGZIP(), []int{2}
}

func (x *VerificationStatusRejectFindIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type VerificationStatusRejectFindIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VerificationStatusReject *VerificationStatusRejectInfo `protobuf:"bytes,1,opt,name=verification_status_reject,json=verificationStatusReject,proto3" json:"verification_status_reject,omitempty"`
}

func (x *VerificationStatusRejectFindIDResponse) Reset() {
	*x = VerificationStatusRejectFindIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_verification_status_reject_verification_status_reject_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerificationStatusRejectFindIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationStatusRejectFindIDResponse) ProtoMessage() {}

func (x *VerificationStatusRejectFindIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_verification_status_reject_verification_status_reject_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationStatusRejectFindIDResponse.ProtoReflect.Descriptor instead.
func (*VerificationStatusRejectFindIDResponse) Descriptor() ([]byte, []int) {
	return file_verification_status_reject_verification_status_reject_proto_rawDescGZIP(), []int{3}
}

func (x *VerificationStatusRejectFindIDResponse) GetVerificationStatusReject() *VerificationStatusRejectInfo {
	if x != nil {
		return x.VerificationStatusReject
	}
	return nil
}

type VerificationStatusRejectFindAllRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page  string `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit string `protobuf:"bytes,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *VerificationStatusRejectFindAllRequest) Reset() {
	*x = VerificationStatusRejectFindAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_verification_status_reject_verification_status_reject_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerificationStatusRejectFindAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationStatusRejectFindAllRequest) ProtoMessage() {}

func (x *VerificationStatusRejectFindAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_verification_status_reject_verification_status_reject_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationStatusRejectFindAllRequest.ProtoReflect.Descriptor instead.
func (*VerificationStatusRejectFindAllRequest) Descriptor() ([]byte, []int) {
	return file_verification_status_reject_verification_status_reject_proto_rawDescGZIP(), []int{4}
}

func (x *VerificationStatusRejectFindAllRequest) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

func (x *VerificationStatusRejectFindAllRequest) GetLimit() string {
	if x != nil {
		return x.Limit
	}
	return ""
}

type VerificationStatusRejectFindAllResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VerificationStatusRejects []*VerificationStatusRejectInfo `protobuf:"bytes,1,rep,name=verification_status_rejects,json=verificationStatusRejects,proto3" json:"verification_status_rejects,omitempty"`
	Paginations               *pagination.PaginationMaster    `protobuf:"bytes,2,opt,name=paginations,proto3" json:"paginations,omitempty"`
}

func (x *VerificationStatusRejectFindAllResponse) Reset() {
	*x = VerificationStatusRejectFindAllResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_verification_status_reject_verification_status_reject_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerificationStatusRejectFindAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationStatusRejectFindAllResponse) ProtoMessage() {}

func (x *VerificationStatusRejectFindAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_verification_status_reject_verification_status_reject_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationStatusRejectFindAllResponse.ProtoReflect.Descriptor instead.
func (*VerificationStatusRejectFindAllResponse) Descriptor() ([]byte, []int) {
	return file_verification_status_reject_verification_status_reject_proto_rawDescGZIP(), []int{5}
}

func (x *VerificationStatusRejectFindAllResponse) GetVerificationStatusRejects() []*VerificationStatusRejectInfo {
	if x != nil {
		return x.VerificationStatusRejects
	}
	return nil
}

func (x *VerificationStatusRejectFindAllResponse) GetPaginations() *pagination.PaginationMaster {
	if x != nil {
		return x.Paginations
	}
	return nil
}

type VerificationStatusRejectCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *VerificationStatusRejectCreateRequest) Reset() {
	*x = VerificationStatusRejectCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_verification_status_reject_verification_status_reject_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerificationStatusRejectCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationStatusRejectCreateRequest) ProtoMessage() {}

func (x *VerificationStatusRejectCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_verification_status_reject_verification_status_reject_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationStatusRejectCreateRequest.ProtoReflect.Descriptor instead.
func (*VerificationStatusRejectCreateRequest) Descriptor() ([]byte, []int) {
	return file_verification_status_reject_verification_status_reject_proto_rawDescGZIP(), []int{6}
}

func (x *VerificationStatusRejectCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VerificationStatusRejectCreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type VerificationStatusRejectCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreateResponse *VerificationStatusRejectWriteResponse `protobuf:"bytes,1,opt,name=create_response,json=createResponse,proto3" json:"create_response,omitempty"`
}

func (x *VerificationStatusRejectCreateResponse) Reset() {
	*x = VerificationStatusRejectCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_verification_status_reject_verification_status_reject_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerificationStatusRejectCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationStatusRejectCreateResponse) ProtoMessage() {}

func (x *VerificationStatusRejectCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_verification_status_reject_verification_status_reject_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationStatusRejectCreateResponse.ProtoReflect.Descriptor instead.
func (*VerificationStatusRejectCreateResponse) Descriptor() ([]byte, []int) {
	return file_verification_status_reject_verification_status_reject_proto_rawDescGZIP(), []int{7}
}

func (x *VerificationStatusRejectCreateResponse) GetCreateResponse() *VerificationStatusRejectWriteResponse {
	if x != nil {
		return x.CreateResponse
	}
	return nil
}

type VerificationStatusRejectDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *VerificationStatusRejectDeleteRequest) Reset() {
	*x = VerificationStatusRejectDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_verification_status_reject_verification_status_reject_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerificationStatusRejectDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationStatusRejectDeleteRequest) ProtoMessage() {}

func (x *VerificationStatusRejectDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_verification_status_reject_verification_status_reject_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationStatusRejectDeleteRequest.ProtoReflect.Descriptor instead.
func (*VerificationStatusRejectDeleteRequest) Descriptor() ([]byte, []int) {
	return file_verification_status_reject_verification_status_reject_proto_rawDescGZIP(), []int{8}
}

func (x *VerificationStatusRejectDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type VerificationStatusRejectDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeleteResponse *VerificationStatusRejectWriteResponse `protobuf:"bytes,1,opt,name=delete_response,json=deleteResponse,proto3" json:"delete_response,omitempty"`
}

func (x *VerificationStatusRejectDeleteResponse) Reset() {
	*x = VerificationStatusRejectDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_verification_status_reject_verification_status_reject_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerificationStatusRejectDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationStatusRejectDeleteResponse) ProtoMessage() {}

func (x *VerificationStatusRejectDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_verification_status_reject_verification_status_reject_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationStatusRejectDeleteResponse.ProtoReflect.Descriptor instead.
func (*VerificationStatusRejectDeleteResponse) Descriptor() ([]byte, []int) {
	return file_verification_status_reject_verification_status_reject_proto_rawDescGZIP(), []int{9}
}

func (x *VerificationStatusRejectDeleteResponse) GetDeleteResponse() *VerificationStatusRejectWriteResponse {
	if x != nil {
		return x.DeleteResponse
	}
	return nil
}

type VerificationStatusRejectUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *VerificationStatusRejectUpdateRequest) Reset() {
	*x = VerificationStatusRejectUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_verification_status_reject_verification_status_reject_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerificationStatusRejectUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationStatusRejectUpdateRequest) ProtoMessage() {}

func (x *VerificationStatusRejectUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_verification_status_reject_verification_status_reject_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationStatusRejectUpdateRequest.ProtoReflect.Descriptor instead.
func (*VerificationStatusRejectUpdateRequest) Descriptor() ([]byte, []int) {
	return file_verification_status_reject_verification_status_reject_proto_rawDescGZIP(), []int{10}
}

func (x *VerificationStatusRejectUpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VerificationStatusRejectUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VerificationStatusRejectUpdateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type VerificationStatusRejectUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UpdateResponse *VerificationStatusRejectWriteResponse `protobuf:"bytes,1,opt,name=update_response,json=updateResponse,proto3" json:"update_response,omitempty"`
}

func (x *VerificationStatusRejectUpdateResponse) Reset() {
	*x = VerificationStatusRejectUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_verification_status_reject_verification_status_reject_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerificationStatusRejectUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationStatusRejectUpdateResponse) ProtoMessage() {}

func (x *VerificationStatusRejectUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_verification_status_reject_verification_status_reject_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationStatusRejectUpdateResponse.ProtoReflect.Descriptor instead.
func (*VerificationStatusRejectUpdateResponse) Descriptor() ([]byte, []int) {
	return file_verification_status_reject_verification_status_reject_proto_rawDescGZIP(), []int{11}
}

func (x *VerificationStatusRejectUpdateResponse) GetUpdateResponse() *VerificationStatusRejectWriteResponse {
	if x != nil {
		return x.UpdateResponse
	}
	return nil
}

var File_verification_status_reject_verification_status_reject_proto protoreflect.FileDescriptor

var file_verification_status_reject_verification_status_reject_proto_rawDesc = []byte{
	0x0a, 0x3b, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x76, 0x65, 0x72,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x5f, 0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6b,
	0x70, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x70,
	0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5d, 0x0a, 0x25, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a,
	0x08, 0x6d, 0x65, 0x73, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6d, 0x65, 0x73, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x9f, 0x01, 0x0a, 0x1c, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x37, 0x0a, 0x25, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x46, 0x69, 0x6e, 0x64, 0x49, 0x44, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x93, 0x01, 0x0a, 0x26, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x6a, 0x65, 0x63,
	0x74, 0x46, 0x69, 0x6e, 0x64, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x69, 0x0a, 0x1a, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x6b, 0x70, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x18, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x52, 0x0a, 0x26, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0xd9,
	0x01, 0x0a, 0x27, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x46, 0x69, 0x6e, 0x64, 0x41,
	0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6b, 0x0a, 0x1b, 0x76, 0x65,
	0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x5f, 0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x2b, 0x2e, 0x6b, 0x70, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x19, 0x76, 0x65,
	0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x12, 0x41, 0x0a, 0x0b, 0x70, 0x61, 0x67, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6b,
	0x70, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x67,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x52, 0x0b, 0x70,
	0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x5d, 0x0a, 0x25, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x87, 0x01, 0x0a, 0x26, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d, 0x0a, 0x0f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x34, 0x2e,
	0x6b, 0x70, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x52, 0x0e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x37, 0x0a, 0x25, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x87, 0x01, 0x0a,
	0x26, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d, 0x0a, 0x0f, 0x64, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x34, 0x2e, 0x6b, 0x70, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0e, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x6d, 0x0a, 0x25, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x6a, 0x65,
	0x63, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x87, 0x01, 0x0a, 0x26, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x6a, 0x65,
	0x63, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x5d, 0x0a, 0x0f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x6b, 0x70, 0x6d, 0x61,
	0x73, 0x74, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x6a, 0x65,
	0x63, 0x74, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52,
	0x0e, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6a,
	0x6f, 0x6f, 0x6e, 0x74, 0x61, 0x2f, 0x6b, 0x70, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_verification_status_reject_verification_status_reject_proto_rawDescOnce sync.Once
	file_verification_status_reject_verification_status_reject_proto_rawDescData = file_verification_status_reject_verification_status_reject_proto_rawDesc
)

func file_verification_status_reject_verification_status_reject_proto_rawDescGZIP() []byte {
	file_verification_status_reject_verification_status_reject_proto_rawDescOnce.Do(func() {
		file_verification_status_reject_verification_status_reject_proto_rawDescData = protoimpl.X.CompressGZIP(file_verification_status_reject_verification_status_reject_proto_rawDescData)
	})
	return file_verification_status_reject_verification_status_reject_proto_rawDescData
}

var file_verification_status_reject_verification_status_reject_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_verification_status_reject_verification_status_reject_proto_goTypes = []interface{}{
	(*VerificationStatusRejectWriteResponse)(nil),   // 0: kpmasterproto.VerificationStatusRejectWriteResponse
	(*VerificationStatusRejectInfo)(nil),            // 1: kpmasterproto.VerificationStatusRejectInfo
	(*VerificationStatusRejectFindIDRequest)(nil),   // 2: kpmasterproto.VerificationStatusRejectFindIDRequest
	(*VerificationStatusRejectFindIDResponse)(nil),  // 3: kpmasterproto.VerificationStatusRejectFindIDResponse
	(*VerificationStatusRejectFindAllRequest)(nil),  // 4: kpmasterproto.VerificationStatusRejectFindAllRequest
	(*VerificationStatusRejectFindAllResponse)(nil), // 5: kpmasterproto.VerificationStatusRejectFindAllResponse
	(*VerificationStatusRejectCreateRequest)(nil),   // 6: kpmasterproto.VerificationStatusRejectCreateRequest
	(*VerificationStatusRejectCreateResponse)(nil),  // 7: kpmasterproto.VerificationStatusRejectCreateResponse
	(*VerificationStatusRejectDeleteRequest)(nil),   // 8: kpmasterproto.VerificationStatusRejectDeleteRequest
	(*VerificationStatusRejectDeleteResponse)(nil),  // 9: kpmasterproto.VerificationStatusRejectDeleteResponse
	(*VerificationStatusRejectUpdateRequest)(nil),   // 10: kpmasterproto.VerificationStatusRejectUpdateRequest
	(*VerificationStatusRejectUpdateResponse)(nil),  // 11: kpmasterproto.VerificationStatusRejectUpdateResponse
	(*timestamppb.Timestamp)(nil),                   // 12: google.protobuf.Timestamp
	(*pagination.PaginationMaster)(nil),             // 13: kpmasterproto.PaginationMaster
}
var file_verification_status_reject_verification_status_reject_proto_depIdxs = []int32{
	12, // 0: kpmasterproto.VerificationStatusRejectInfo.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 1: kpmasterproto.VerificationStatusRejectFindIDResponse.verification_status_reject:type_name -> kpmasterproto.VerificationStatusRejectInfo
	1,  // 2: kpmasterproto.VerificationStatusRejectFindAllResponse.verification_status_rejects:type_name -> kpmasterproto.VerificationStatusRejectInfo
	13, // 3: kpmasterproto.VerificationStatusRejectFindAllResponse.paginations:type_name -> kpmasterproto.PaginationMaster
	0,  // 4: kpmasterproto.VerificationStatusRejectCreateResponse.create_response:type_name -> kpmasterproto.VerificationStatusRejectWriteResponse
	0,  // 5: kpmasterproto.VerificationStatusRejectDeleteResponse.delete_response:type_name -> kpmasterproto.VerificationStatusRejectWriteResponse
	0,  // 6: kpmasterproto.VerificationStatusRejectUpdateResponse.update_response:type_name -> kpmasterproto.VerificationStatusRejectWriteResponse
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_verification_status_reject_verification_status_reject_proto_init() }
func file_verification_status_reject_verification_status_reject_proto_init() {
	if File_verification_status_reject_verification_status_reject_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_verification_status_reject_verification_status_reject_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerificationStatusRejectWriteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_verification_status_reject_verification_status_reject_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerificationStatusRejectInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_verification_status_reject_verification_status_reject_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerificationStatusRejectFindIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_verification_status_reject_verification_status_reject_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerificationStatusRejectFindIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_verification_status_reject_verification_status_reject_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerificationStatusRejectFindAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_verification_status_reject_verification_status_reject_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerificationStatusRejectFindAllResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_verification_status_reject_verification_status_reject_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerificationStatusRejectCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_verification_status_reject_verification_status_reject_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerificationStatusRejectCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_verification_status_reject_verification_status_reject_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerificationStatusRejectDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_verification_status_reject_verification_status_reject_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerificationStatusRejectDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_verification_status_reject_verification_status_reject_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerificationStatusRejectUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_verification_status_reject_verification_status_reject_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerificationStatusRejectUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_verification_status_reject_verification_status_reject_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_verification_status_reject_verification_status_reject_proto_goTypes,
		DependencyIndexes: file_verification_status_reject_verification_status_reject_proto_depIdxs,
		MessageInfos:      file_verification_status_reject_verification_status_reject_proto_msgTypes,
	}.Build()
	File_verification_status_reject_verification_status_reject_proto = out.File
	file_verification_status_reject_verification_status_reject_proto_rawDesc = nil
	file_verification_status_reject_verification_status_reject_proto_goTypes = nil
	file_verification_status_reject_verification_status_reject_proto_depIdxs = nil
}
