// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: installment/installment.proto

package installment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InstallmentPagination struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrentPage int32 `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	Limit       int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset      int32 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	TotalPages  int32 `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	NextPage    int32 `protobuf:"varint,5,opt,name=next_page,json=nextPage,proto3" json:"next_page,omitempty"`
	PrevPage    int32 `protobuf:"varint,6,opt,name=prev_page,json=prevPage,proto3" json:"prev_page,omitempty"`
	TotalPage   int32 `protobuf:"varint,7,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`
	TotalData   int32 `protobuf:"varint,8,opt,name=total_data,json=totalData,proto3" json:"total_data,omitempty"`
}

func (x *InstallmentPagination) Reset() {
	*x = InstallmentPagination{}
	if protoimpl.UnsafeEnabled {
		mi := &file_installment_installment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstallmentPagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallmentPagination) ProtoMessage() {}

func (x *InstallmentPagination) ProtoReflect() protoreflect.Message {
	mi := &file_installment_installment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallmentPagination.ProtoReflect.Descriptor instead.
func (*InstallmentPagination) Descriptor() ([]byte, []int) {
	return file_installment_installment_proto_rawDescGZIP(), []int{0}
}

func (x *InstallmentPagination) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *InstallmentPagination) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *InstallmentPagination) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *InstallmentPagination) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *InstallmentPagination) GetNextPage() int32 {
	if x != nil {
		return x.NextPage
	}
	return 0
}

func (x *InstallmentPagination) GetPrevPage() int32 {
	if x != nil {
		return x.PrevPage
	}
	return 0
}

func (x *InstallmentPagination) GetTotalPage() int32 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

func (x *InstallmentPagination) GetTotalData() int32 {
	if x != nil {
		return x.TotalData
	}
	return 0
}

type InstallmentInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	UdpatedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=udpated_at,json=udpatedAt,proto3" json:"udpated_at,omitempty"`
}

func (x *InstallmentInfo) Reset() {
	*x = InstallmentInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_installment_installment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstallmentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallmentInfo) ProtoMessage() {}

func (x *InstallmentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_installment_installment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallmentInfo.ProtoReflect.Descriptor instead.
func (*InstallmentInfo) Descriptor() ([]byte, []int) {
	return file_installment_installment_proto_rawDescGZIP(), []int{1}
}

func (x *InstallmentInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InstallmentInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InstallmentInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InstallmentInfo) GetUdpatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UdpatedAt
	}
	return nil
}

type InstallmentFindIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *InstallmentFindIDRequest) Reset() {
	*x = InstallmentFindIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_installment_installment_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstallmentFindIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallmentFindIDRequest) ProtoMessage() {}

func (x *InstallmentFindIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_installment_installment_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallmentFindIDRequest.ProtoReflect.Descriptor instead.
func (*InstallmentFindIDRequest) Descriptor() ([]byte, []int) {
	return file_installment_installment_proto_rawDescGZIP(), []int{2}
}

func (x *InstallmentFindIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type InstallmentFindIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Installment *InstallmentInfo `protobuf:"bytes,1,opt,name=installment,proto3" json:"installment,omitempty"`
}

func (x *InstallmentFindIDResponse) Reset() {
	*x = InstallmentFindIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_installment_installment_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstallmentFindIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallmentFindIDResponse) ProtoMessage() {}

func (x *InstallmentFindIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_installment_installment_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallmentFindIDResponse.ProtoReflect.Descriptor instead.
func (*InstallmentFindIDResponse) Descriptor() ([]byte, []int) {
	return file_installment_installment_proto_rawDescGZIP(), []int{3}
}

func (x *InstallmentFindIDResponse) GetInstallment() *InstallmentInfo {
	if x != nil {
		return x.Installment
	}
	return nil
}

type InstallmentFindAllRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page  string `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit string `protobuf:"bytes,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *InstallmentFindAllRequest) Reset() {
	*x = InstallmentFindAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_installment_installment_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstallmentFindAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallmentFindAllRequest) ProtoMessage() {}

func (x *InstallmentFindAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_installment_installment_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallmentFindAllRequest.ProtoReflect.Descriptor instead.
func (*InstallmentFindAllRequest) Descriptor() ([]byte, []int) {
	return file_installment_installment_proto_rawDescGZIP(), []int{4}
}

func (x *InstallmentFindAllRequest) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

func (x *InstallmentFindAllRequest) GetLimit() string {
	if x != nil {
		return x.Limit
	}
	return ""
}

type InstallmentFindAllResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Installments []*InstallmentInfo     `protobuf:"bytes,1,rep,name=installments,proto3" json:"installments,omitempty"`
	Paginations  *InstallmentPagination `protobuf:"bytes,2,opt,name=paginations,proto3" json:"paginations,omitempty"`
}

func (x *InstallmentFindAllResponse) Reset() {
	*x = InstallmentFindAllResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_installment_installment_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstallmentFindAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallmentFindAllResponse) ProtoMessage() {}

func (x *InstallmentFindAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_installment_installment_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallmentFindAllResponse.ProtoReflect.Descriptor instead.
func (*InstallmentFindAllResponse) Descriptor() ([]byte, []int) {
	return file_installment_installment_proto_rawDescGZIP(), []int{5}
}

func (x *InstallmentFindAllResponse) GetInstallments() []*InstallmentInfo {
	if x != nil {
		return x.Installments
	}
	return nil
}

func (x *InstallmentFindAllResponse) GetPaginations() *InstallmentPagination {
	if x != nil {
		return x.Paginations
	}
	return nil
}

var File_installment_installment_proto protoreflect.FileDescriptor

var file_installment_installment_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x69, 0x6e,
	0x73, 0x74, 0x61, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0d, 0x6b, 0x70, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x81, 0x02, 0x0a, 0x15, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x50,
	0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x6e,
	0x65, 0x78, 0x74, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x6e, 0x65, 0x78, 0x74, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x72, 0x65, 0x76,
	0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x72, 0x65,
	0x76, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x70,
	0x61, 0x67, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x50, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x44,
	0x61, 0x74, 0x61, 0x22, 0x92, 0x01, 0x0a, 0x0f, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x6d,
	0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x39, 0x0a,
	0x0a, 0x75, 0x64, 0x70, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75,
	0x64, 0x70, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x2a, 0x0a, 0x18, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x6e, 0x64, 0x49, 0x44, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x5d, 0x0a, 0x19, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x6d,
	0x65, 0x6e, 0x74, 0x46, 0x69, 0x6e, 0x64, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x40, 0x0a, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6b, 0x70, 0x6d, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x6d, 0x65,
	0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x6d,
	0x65, 0x6e, 0x74, 0x22, 0x45, 0x0a, 0x19, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x6d, 0x65,
	0x6e, 0x74, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0xa8, 0x01, 0x0a, 0x1a, 0x49,
	0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x0c, 0x69, 0x6e, 0x73,
	0x74, 0x61, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x6b, 0x70, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x0c, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x46, 0x0a,
	0x0b, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6b, 0x70, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x61,
	0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6a, 0x6f, 0x6f, 0x6e, 0x74, 0x61, 0x2f, 0x6b, 0x70, 0x6d, 0x61,
	0x73, 0x74, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c,
	0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_installment_installment_proto_rawDescOnce sync.Once
	file_installment_installment_proto_rawDescData = file_installment_installment_proto_rawDesc
)

func file_installment_installment_proto_rawDescGZIP() []byte {
	file_installment_installment_proto_rawDescOnce.Do(func() {
		file_installment_installment_proto_rawDescData = protoimpl.X.CompressGZIP(file_installment_installment_proto_rawDescData)
	})
	return file_installment_installment_proto_rawDescData
}

var file_installment_installment_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_installment_installment_proto_goTypes = []interface{}{
	(*InstallmentPagination)(nil),      // 0: kpmasterproto.InstallmentPagination
	(*InstallmentInfo)(nil),            // 1: kpmasterproto.InstallmentInfo
	(*InstallmentFindIDRequest)(nil),   // 2: kpmasterproto.InstallmentFindIDRequest
	(*InstallmentFindIDResponse)(nil),  // 3: kpmasterproto.InstallmentFindIDResponse
	(*InstallmentFindAllRequest)(nil),  // 4: kpmasterproto.InstallmentFindAllRequest
	(*InstallmentFindAllResponse)(nil), // 5: kpmasterproto.InstallmentFindAllResponse
	(*timestamppb.Timestamp)(nil),      // 6: google.protobuf.Timestamp
}
var file_installment_installment_proto_depIdxs = []int32{
	6, // 0: kpmasterproto.InstallmentInfo.udpated_at:type_name -> google.protobuf.Timestamp
	1, // 1: kpmasterproto.InstallmentFindIDResponse.installment:type_name -> kpmasterproto.InstallmentInfo
	1, // 2: kpmasterproto.InstallmentFindAllResponse.installments:type_name -> kpmasterproto.InstallmentInfo
	0, // 3: kpmasterproto.InstallmentFindAllResponse.paginations:type_name -> kpmasterproto.InstallmentPagination
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_installment_installment_proto_init() }
func file_installment_installment_proto_init() {
	if File_installment_installment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_installment_installment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstallmentPagination); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_installment_installment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstallmentInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_installment_installment_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstallmentFindIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_installment_installment_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstallmentFindIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_installment_installment_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstallmentFindAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_installment_installment_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstallmentFindAllResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_installment_installment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_installment_installment_proto_goTypes,
		DependencyIndexes: file_installment_installment_proto_depIdxs,
		MessageInfos:      file_installment_installment_proto_msgTypes,
	}.Build()
	File_installment_installment_proto = out.File
	file_installment_installment_proto_rawDesc = nil
	file_installment_installment_proto_goTypes = nil
	file_installment_installment_proto_depIdxs = nil
}
